spring:
  application:
    name: rest-spring-vehicle

  datasource:
    user: root
    password: 123
    url: jdbc:postgresql://localhost:15432/vehicle
    driver: org.postgresql.Driver
    dbCreate: update
  jpa:
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql


hibernate:
  show_sql: true
  format_sql: true
  hbm2ddl.auto: validate
  dialect: org.hibernate.dialect.PostgresPlusDialect

